### ISSUE TITLE
Semantic versioning with comment (e.g. 4.0.0-comment) after patch not working with IG Publisher

### ISSUE THREAD

**Issue by oliveregger** [IHE/ITI.MHD#11]
**Issue** 

package name 4.0.0-comment does not work with IG Publisher for dependent packages: Failed to resolve package ihe.mhd.fhir#4.0.0-comment from server: http://packages.fhir.org and  Error reading http://ihe.net/fhir/ihe.mhd.fhir/4.0.0-comment/package.tgz 

The issue is that current tooling does not accept suffix -comment (pre-release and build metadata) 

**Proposed Change** 
For this review no issues since master branch is the same, however for a next version it would be helpful to have a specific version for pubic commit. 

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by JohnMoehrke** [comment]
I thought that this was the recommendation... the published version coming out of comment resolution will be 4.0.0, so the problem should be short lived. Presumably the IG-Publisher will eventually have some kind of support for this concept.

**Comment by JohnMoehrke** [comment]
I think the other problem is that I failed to send in the ig-registry pull-request. It was not part of the process documentation so I failed to do it. Now my pull-request is behind.

**Comment by JohnMoehrke** [comment]
also, IHE tends not to archive the public-comment version... so this will go away with final publication.

**Comment by JohnMoehrke** [comment]
@oliveregger indicates there is a RSS method for IHE as a whole to publish new IG.
