### ISSUE TITLE
DocumentReference.content definition

### ISSUE THREAD

**Issue by skbhaskarla** [IHE/ITI.MHD#110]
IHE MHD 4.0.2
[37. DocumentReference.content](https://profiles.ihe.net/ITI/MHD/StructureDefinition-IHE.MHD.Minimal.DocumentReference-definitions.html#DocumentReference.content)
The following definition "There may be multiple content element repetitions, each with a different format." does not agree with `Control	1..1`

**Comment by JohnMoehrke** [comment]
the definition comes from FHIR core, MHD is adding the constraint to 1..1.

We could overwrite the definition, and likely would be helpful to add comment that where transforms are needed to use the MHD defined transform method.

**Comment by skbhaskarla** [comment]
The base FHIR definition does not apply after the `Control 1..1` is introduced by MHD profile, I think the MHD definition should be fixed.

**Comment by JohnMoehrke** [comment]
I do not understand. Please be specific

**Comment by JohnMoehrke** [comment]
are you referring to the fact that the MustSupport flag is set in the Minimal Metadata, and when Comprehensive Metadata is derived off of that and increases the cardinality to 1..1; that the MustSupport is still set? And this seems to be indicating a conflict as the element is both marked mandatory and also MustSupport?

**Comment by JohnMoehrke** [comment]
such as the .type element in Comprehensive?

**Comment by skbhaskarla** [comment]
Hi John,

No, this issue has nothing to do with MustSupport.

Let me explain, the FHIR DocumentReference resource Content element's definition matches it cardinality of 1..*, i.e.: There may be MULTIPLE content element repetitions, each with a different format. (Emphasis added.) 

FHIR Reference: https://hl7.org/fhir/documentreference-definitions.html#DocumentReference.content

Now, in the MHD DocumentReference, the Content element cardinality was restricted to ONE element of content (or 1..1) but the Content element description was not updated, it still says "multiple element repetitions," which is not correct.

MHD Reference: https://profiles.ihe.net/ITI/MHD/StructureDefinition-IHE.MHD.Minimal.DocumentReference-definitions.html#DocumentReference.content

Sunil

**Comment by JohnMoehrke** [comment]
so the issue is about the description saying multiple, while we have constrained it to ONE.
