### ISSUE TITLE
Simplified Publish

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.MHD#122]
Prefer that there be a way a Document Source can publish simply using one DocumentReference. This DocumentReference would use attachment.data holding the data. The Document Recipient is allowed to breakout the .data into a Binary and change to .url (may simply be guidance).
- when a SubmissionSet is needed by the recipient, it is derived off of the metadata in the DocumentReference
  - meaning there is no way to carry elements unique to SubmissionSet, (e.g. intended recipient)
  - there is no way to have metadata different than DocumentReference (submitter is the author)
- no way for this to be a replacement
- named option to be visible and hold conditions.

Likely could be supported by RESTful POST of the DocumentReference.

**Comment by JohnMoehrke** [comment]
@oliveregger how do you think we should implement this? Should we
a. relax the requirements of ITI-65
b. crate another transaction ITI-??? that is this lesser version?

How would we handle the server capabilityStatement? Would we start adding in something that enables a client to understand the minimal requirements of the server? (This might be useful even today regarding minimal, comprehensive, unconntained, and xds-on-fhir.

**Comment by JohnMoehrke** [comment]
make a new transaction

**Comment by sheridancook** [comment]
We would encourage consideration of an even more simplified transaction that allows a FHIR Document to be published without the DocumentReference. In our evaluation of MHD for Pan-Canadian Patient Summary - it was unclear if DocumentReference was necessitated for the benefit of XDS systems requiring the submission set metadata. See comment in #123 - if value of having a DocumentReference varies by implementer (and an operation is available to allow implementers the ability to generate the metadata they need after submission) then DocumentReference should be considered optional with avenues to submit FHIR Document alone
