### ISSUE TITLE
Status mapping table feels out of place

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.MHD#124]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

Tables 2:3.66.4.1.2.1-1

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

This table maps List.status to the ebRIM codes that would be used for SubmissionSets and Folders. The table is fine, but it's current placement in the spec feels wrong and overly intimidating to those that are not implementing MHD as an API to XDS. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Move the table down below into section 2:3.66.4.1.3.1 where other mapping tables live. 

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by JohnMoehrke** [comment]
excellent suggestion.
