### ISSUE TITLE
ITI-66/ITI-67: lower bound modifier for dates

### ISSUE THREAD

**Issue by qligier** [IHE/ITI.MHD#129]
**Section Number** 2:3.66.4.1.3.1 and 2:3.67.4.1.3.1

**Issue** Note 1 of XDS on FHIR says:

> Note 1: This (FindSubmissionSets|FindDocuments) parameter is used when the greater than parameter modifier is used on the created parameter.

That would give the following semantic:

> date[gt] < DocumentReference.date < date[lt]

But IHE TF-2a 3.18.4.1.2.3.3 gives the following, different search parameters semantic:

> $XDSDocumentEntryCreationTimeFrom <= XDSDocumentEntry.creationTime < $XDSDocumentEntryCreationTimeTo

So, to keep compatibility with ITI-18, the lower bound should use the _greater than or equal_ modifier.

**Proposed Change** The note should be updated to say:

> Note 1: This (FindSubmissionSets|FindDocuments) parameter is used when the **greater than or equal** parameter modifier is used on the created parameter.

The note 2 is not updated.

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by JohnMoehrke** [comment]
look for history on ITI-18 vs ITI-66. may be a CP that covered this, or affects this.

**Comment by qligier** [comment]
That would be CP-ITI-1254: https://docs.google.com/document/d/1-jh3uABTnXhBksJQFTX0CyVJi54xLpMY/
