### ISSUE TITLE
List.identifier should differentiate SubmissionSet.entryUUID and SubmissionSet.uniqueId

### ISSUE THREAD

**Issue by oliveregger** [IHE/ITI.MHD#13]
**Section Number** 
https://profiles.ihe.net/ITI/MHD/StructureDefinition-IHE.MHD.Comprehensive.SubmissionSet-mappings.html

**Issue** 
identifier is mapped to SubmissionSet.entryUUID and SubmissionSet.uniqueId

it is not clear how the identifier should be mapped to entryUUID or uniqueId, it could be differentiated by oid/uuid but this seems not obvious.

**Proposed Change** 

For MHD Rev. 3.2 – 2020-08-28 it was specified for **Folder** that "When the List.identifier carries the entryUUID, then the List.identifier.use shall be ‘official’. When the List.identifier carries the uniqueId, then the List.identifier.use shall be ‘usual’.", I propose this concept should be incorporated in the MHD List profile for Folder and SubmissionSet.

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by JohnMoehrke** [comment]
thanks. Good solution. I don't think we can demand cardinality as your pull-request does. but the slicing pattern is good. Likely need narrative too.
