### ISSUE TITLE
Adjust Transaction Number for Document References Responses

### ISSUE THREAD

**Issue by oliveregger** [IHE/ITI.MHD#15]
**Section Number** 
https://profiles.ihe.net/ITI/MHD/StructureDefinition-IHE.MHD.FindDocumentReferencesComprehensiveResponseMessage.html
https://profiles.ihe.net/ITI/MHD/StructureDefinition-IHE.MHD.FindDocumentReferencesResponseMessage.html

**Issue** 
Should be ITI-67 instead of ITI-68

**Proposed Change** *
PR

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by JohnMoehrke** [comment]
thanks
