### ISSUE TITLE
MHD 4.1.0 Issues page not update to date

### ISSUE THREAD

**Issue by skbhaskarla** [IHE/ITI.MHD#152]
In the current publication of the IHE MHD (4.1.0), [MHD Home page](https://profiles.ihe.net/ITI/MHD/index.html#mhd-home), there is a Note that says "Significant Changes, Open, and Closed Issues" but it does not appear that this page was updated to reflect the changes between 4.1.0 and the previous version. For example, the canonical URL of the MHD Minimal Metadata Profile changed from [http](https://profiles.ihe.net/ITI/MHD/4.0.1/ITI-65.html#23654121-bundle-resources) to [https](https://profiles.ihe.net/ITI/MHD/4.1.0/ITI-65.html#23654121-bundle-resources) . The [Closed Issues](https://profiles.ihe.net/ITI/MHD/4.1.0/a_issues.html) section only back to MHD 4.0. I was expecting to find updates in the [Issues page](https://profiles.ihe.net/ITI/MHD/a_issues.html). Is it possible to update the Issues page? (As an alternative, I checked the MHD GitHub page, there is no way to coordinate between the releases and issues involved in the release.)

**Comment by JohnMoehrke** [comment]
Sorry that the issues.html page failed to include sufficient detail. I
really intended to put most things there. I likely would have missed the
https thing, as that was applied to all IHE implementation guides.  You can
get a more detailed delta at the github release pin

https://github.com/IHE/ITI.MHD/releases/tag/v4.1.0

on the releases tag you can also compare to other releases (github compare,
so it is at the source level), this also includes the issues that were
addressed

for example between 4.1.0 and 4.0.2
    https://github.com/IHE/ITI.MHD/compare/4.0.2...v4.1.0

John Moehrke 🔥 Architect: Healthcare Informatics Standards -
Interoperability, Privacy, and Security
IHE Co-Chair IT Infrastructure Planning and Technical
HL7 Co-Chair Security WG, FHIR FMG, FHIR facilitator, and FHIR Foundation
founding member
Employee of By Light -- Contractor to VHA MyHealtheVet
***@***.***  |  M +1 920-564-2067  |  ***@***.***
 https://healthcaresecprivacy.blogspot.com

**Comment by skbhaskarla** [comment]
If "change id to ihe.iti.mhd to match current id format requirement" is in reference to the following "Official URL" in MHD Home, https://profiles.ihe.net/ITI/MHD/ImplementationGuide/ihe.iti.mhd
Then, this URL does not resolve to a working page when it is entered in a Web browser.

**Comment by JohnMoehrke** [comment]
the canonical URI of an Implementation Guide is not intended to be the same thing as the home page of the Implementation Guide.
