### ISSUE TITLE
Incorrect MHD SubmissionSet Comprehensive List type

### ISSUE THREAD

**Issue by skbhaskarla** [IHE/ITI.MHD#153]
Why is the list type Uncontained ?
![image](https://user-images.githubusercontent.com/2388275/182443931-92ca7439-3bf4-45af-a286-ab0a577de45c.png)

**Comment by JohnMoehrke** [comment]
What you are showing is that the Comprehensive.SubmissionSet is DERIVED FROM the SubmissionSetComphrehensiveUnContained.

This is intentioned. The SubmissionSet for Comprehensive is a specialization (derived from) the SubmissionSet Comprehensive UnContained. It simply forces that the .source element must now be contained.
