### ISSUE TITLE
Please consider allowing replace-logic in ITI-105

### ISSUE THREAD

**Issue by simoneOnFhir** [IHE/ITI.MHD#173]
See discussion on Zulip: https://chat.fhir.org/#narrow/stream/179223-ihe/topic/MHD.20Simplified.20Publish

"We ([ISiK-Specifiers and  Implementers from Germany](https://simplifier.net/spec-isik-dokumentenaustausch)) would love to see the replaces feature maintained in ITI-105. In our use case, amendments or replacements of documents are common occurances but in our opinion don't warrant the complexitiy that comes with ITI-65. We would argue that adding Provenance to the documents doesn't necessarily require a submission set, since many details about the originating client/user/agent/etc. could be derived from HTTP metadata and OAUTH Tokens if needed."

**Comment by JohnMoehrke** [comment]
discussed in ITI-Tech meeting.

will allow transforms including replace.

will add an open-issue asking for specific comment about this. If no comment is received after public-comment then this open-issue will be closed.
