### ISSUE TITLE
build validation warnings

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.MHD#177]
on many (all?) AuditEvent profiling a warning is now thrown in many places

For the complex type Coding, consider using a pattern rather than a fixed value to avoid over-constraining the instance

**Comment by oliveregger** [comment]
I think you can ignore this warning, because you put the fixed value on a slice and there are still multiple codings allowed, e.g. https://build.fhir.org/ig/IHE/ITI.MHD/branches/Improvements-2022/AuditEvent-ex-auditFindDocumentLists-consumer.json.html does not show an error.

**Comment by JohnMoehrke** [comment]
fixed in Improvements branch
