### ISSUE TITLE
Signed documents and canonical JSON/XML with other document sharing profiles

### ISSUE THREAD

**Issue by lukeaduncan** [IHE/ITI.MHD#189]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

2:3.65.4.1.3.1 Grouping with Actors in other Document Sharing Profiles
http://build.fhir.org/ig/IHE/ITI.MHD/branches/Improvements-2022/ITI-65.html#23654131-grouping-with-actors-in-other-document-sharing-profiles

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

Should we specifically call out signing and canonicalization?  The serialization link gets there, but it takes a couple clicks.

http://hl7.org/fhir/R4/json.html#canonical and http://hl7.org/fhir/R4/xml.html#digsig

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Add text linking to those sections if deemed useful.

**Priority**:
- High: Important issue where there is major issue to be resolved. Requires discussion and debate.
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

Medium

**Comment by JohnMoehrke** [comment]
This specific section does point at the FHIR Seralization section.  we can't point only at the json canonicalization. hence why I went to this higher section.

There is no relationship with digital signatures.

no change
