### ISSUE TITLE
Add Profile/Example for a Find Document Lists Response Message

### ISSUE THREAD

**Issue by oliveregger** [IHE/ITI.MHD#19]
**Section Number** 
https://profiles.ihe.net/ITI/MHD/ITI-66.html

**Issue** 
There is no profile for a Find Document Lists Response Message

**Proposed Change** 
Add with upcoming Pull Request.

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by JohnMoehrke** [comment]
thanks

**Comment by JohnMoehrke** [comment]
merged pull request. Is it important to have the query response this tightly profiled? I worry that the tightness might make this more difficult to use with too tight of expectations.
