### ISSUE TITLE
FHIR documents in simplified publish (ITI-105)

### ISSUE THREAD

**Issue by lukeaduncan** [IHE/ITI.MHD#190]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

2:3.105.4.1.3 Expected Actions
http://build.fhir.org/ig/IHE/ITI.MHD/branches/Improvements-2022/ITI-105.html#23105413-expected-actions

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

Should this also include the FHIR Document option?  Allowing the second paragraph:

On receipt of the Simplified Publish Request Message, the Document Recipient shall validate the DocumentReference resource provided, extract the document from the DocumentReference.content.attachment.data element, create a Binary and SubmissionSet derived off of the DocumentReference, and respond with one of the HTTP codes defined in the response [Message Semantics](http://build.fhir.org/ig/IHE/ITI.MHD/branches/Improvements-2022/ITI-105.html#23105412-message-semantics).

to include Bundle or Binary?

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

**Priority**:
- High: Important issue where there is major issue to be resolved. Requires discussion and debate.
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

Medium

**Comment by JohnMoehrke** [comment]
I am not sure that is a good idea, and it is not clear to me how simplified the result will be. The .data element in DocumentReference already requires base64 encoding, so there is very little benefit to including a FHIR Document Bundle. 

Adding this kind of support might simply setup too many ways to do the exact same thing.

This said, the text as it stands today could be used to put a FHIR Document Bundle into the .data element; it would be extracted just like mentioned. Thus I am not sure that the current text does not already express what you are asking for simply without saying so.

need to discuss

**Comment by JohnMoehrke** [comment]
discussed in ITI-Tech meeting. Agree that this is not needed, that there are enough ways to provide a FHIR-Document.
