### ISSUE TITLE
ITI-64 FHIR documents Publish Option Named With Wrong Transaction

### ISSUE THREAD

**Issue by slagesse-epic** [IHE/ITI.MHD#191]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*

1:33.2 Table 1:33.2-1

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*

Table 1:33.2-1 lists the Fhir Documents Publish option as "ITI-64 FHIR documents Publish". It should be ITI-65. 

**Proposed Change** *Propose a resolution to your issue (e.g., suggested new wording or description of a way to address the issue). The committee might simply accept your suggested text. Even if they don't, it gives a good sense of what you are looking for. Leaving this blank means you can't imagine how to resolve the issue, which makes it easier for the committee to admit they can't imagine how to resolve it either and leave it unresolved.*

Change to "ITI-65 FHIR Documents Publish Option"

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by JohnMoehrke** [comment]
thanks
