### ISSUE TITLE
Indicate how to write comment on the home page of the guide

### ISSUE THREAD

**Issue by nriss** [IHE/ITI.MHD#203]
**Section Number** *Identify the most specific section number the issue occurs (e.g. 4.1.2)*
MHD HOME

**Issue** *Describe your issue. Don't write a book, but do include enough to indicate what you see as a problem.*
Could be cool to add a link on the home page (or somewhere else on the guide?) to indicate how to participate / where can we write comments about it: should we use GitHub issues ? 

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

Moreover, we are implementing a simplified publish inspired by the new IHE MHD publication in France, so thanks a lot for your work :)
https://participez.esante.gouv.fr/project/mon-espace-sante-specifications-des-api-dinteroperabilite/presentation/presentation
(And soon, an IG will be proposed :))

**Comment by JohnMoehrke** [comment]
The footer on each page of these publications has what you are looking for,  a link to use to create "New Issue", another to review "Issues"; and there is a third link for "Propose a change".
