### ISSUE TITLE
MHD 4.2.0 entryUUID 

### ISSUE THREAD

**Issue by skbhaskarla** [IHE/ITI.MHD#206]
MHD 4.2.0 
ITI-65 
2:3.65.4.1.2 Message Semantics

Two questions

1. What is the reason for the change in https://github.com/IHE/ITI.MHD/issues/167? It is not explicitly stated in the GitHub ticket. I can make assumptions but would like the why part logged in the ticket for reference.

2. What is the expected behavior when Document Source does indeed provide an entryUUID value, for example, a SubmissionSet entryUUID?

**Comment by JohnMoehrke** [comment]
addressed the first question on the other issue. SubmissionSet allows entryUUID.
