### ISSUE TITLE
Add Profile/Example for a Provide Document Bundle Response Message

### ISSUE THREAD

**Issue by oliveregger** [IHE/ITI.MHD#21]
**Section Number** 
https://profiles.ihe.net/ITI/MHD/ITI-65.html

**Issue** 
There is no profile/example for a Provide Document Bundle Response Message

**Proposed Change** 
PR with profile/example

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by JohnMoehrke** [comment]
thanks
