### ISSUE TITLE
Invariant iti-mhd-repl is incomplete

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.MHD#213]
I had to fixup the invariant with a newer IG publisher, but during the fixing of it to make the publisher happy, I came to the realization that the logic was not matching the fhirpath expression. And it was not complete.

today:
```
Invariant:   iti-mhd-repl
Description: "a DocumetReference replacements needs to relate to a superseded DocumentReference"
Expression:  "code='replaces' implies target.exists()"
Severity:    #error

```

Yet the invariant should actually be checking deeper. It really says that if the .code is `replaces` that the .target must point at a DocumentReference that is `superceded`

```
relatesTo.target.resolve().status=superseded
```

but if we had this, we really should be checking that all the others are pointing at `current` DocumentReference.

```
relatesTo.target.resolve().status=current
```

Then, I find out that it is generally not recommended to include resolve() in an invariant.

see zulip chat https://chat.fhir.org/#narrow/stream/179266-fhirpath/topic/help.20with.20code.20is

**Comment by JohnMoehrke** [comment]
is this invariant only intended to be used in an ITI-65 Transaction Bundle?

**Comment by lukeaduncan** [comment]
I found something so perhaps like this?  I haven't done any validation on this, but maybe it's close.  I'm not sure we can really rely on the id though.

entry.resource.where(is(DocumentReference) and status = 'superseded').id = entry.resource.where(is(DocumentReference) and relatesTo.code = 'replaces').relatesTo.target.reference.replace('DocumentReference/','')

**Comment by lukeaduncan** [comment]
Discussed in committee and will resolve by removing the invariant as stated today as it is redundant.

**Comment by oliveregger** [comment]
@lukeaduncan why is it redundant?

**Comment by JohnMoehrke** [comment]
Because the fhir core already requires them to be populated
