### ISSUE TITLE
AuditEvent.entity slice is closed

### ISSUE THREAD

**Issue by qligier** [IHE/ITI.MHD#220]
**Section Number**
[StructureDefinition/IHE.MHD.ProvideBundle.Audit.Recipient](https://profiles.ihe.net/ITI/MHD/StructureDefinition-IHE.MHD.ProvideBundle.Audit.Recipient.html)
[StructureDefinition/IHE.MHD.ProvideBundle.Audit.Source](https://profiles.ihe.net/ITI/MHD/StructureDefinition-IHE.MHD.ProvideBundle.Audit.Source.html)

**Issue**
The slice on `AuditEvent.entity` is closed. It prevents adding entities (such as those described in BALP).
That slice in other AuditEvent profiles is opened.

**Proposed Change**
Open the slice.

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by JohnMoehrke** [comment]
What is your use-case for adding more entity? It is closed because that is the two entities that are appropriate.

**Comment by qligier** [comment]
We want to add an entity for the transaction identifier (tracecontext) in the AuditEvent. It is related to https://github.com/IHE/ITI.BasicAudit/pull/100

For example, in IHE.MHD.SimplifiedPublish.Audit.Recipient:

- the slice is open;
- there's a slice for entity:transaction, but it only supports XRequestId (this is another issue, but the open slice makes it non-blocking).

In IHE.MHD.ProvideBundle.Audit.Recipient/IHE.MHD.ProvideBundle.Audit.Source:

- the slice is closed;
- there's no slice for entity:transaction.

Why the difference?

**Comment by JohnMoehrke** [comment]
Thank you.

**Comment by JohnMoehrke** [comment]
Let me know if this pull-request meets your needs. This pull-request will need committee review, may require a CP.

**Comment by qligier** [comment]
Hi @JohnMoehrke! Yes, that would allow us to create another slice for our use, thanks!
Let me know if there's a need to write a CP.
