### ISSUE TITLE
Example List reference to itself wrong?

### ISSUE THREAD

**Issue by oliveregger** [IHE/ITI.MHD#23]
**Section Number** 
https://profiles.ihe.net/ITI/MHD/List-593cd04e-b696-45c1-bc32-39e55a340a45.json.html

**Issue** 
entry.item.reference points to the example list instance itself (593cd04e-b696-45c1-bc32-39e55a340a46), should this not be to a DocumentReference?

**Proposed Change** *
Fix example

**Priority**:
- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by JohnMoehrke** [comment]
I think this is a Folder (0a45) that points at a DocumentReference (0a46)
see https://github.com/IHE/ITI.MHD/blob/master/input/fsh/ex-ProvideBundles.fsh

No question there is room for better clarity.

**Comment by oliveregger** [comment]
missed the uid + 1 change, sorry. i close the issue
