### ISSUE TITLE
MHD_053: assuring query results are all the same human patient

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.MHD#30]
MHD_053: Note that there is an emerging issue that FHIR has not addressed and that is how distributed systems behave, and how Patient links affect recorded data. Thus, it is difficult to determine today that the response Bundle content all will be pointing at the exact same Patient, although they should all be referring to the same human.

**Comment by JohnMoehrke** [comment]
Not clear there is anything that can be done with this. Also not sure anything should be done with this. it is up to the server to assure, to the best of the servers ability, that the results are about the same patient. And it is equally true that the client must presume this to be the case. This is the way it is done in XCA. In MHDS and XDS this is driven to be true thru unified patient identity that is centrally managed (XDS Affinity Domain, PMIR golden identity).

**Comment by djritz** [comment]
Is there a thread on Zulip that could be referenced, here? It may be helpful to see how this emerging issue has been characterized... and what has been the discussion so far.

**Comment by JohnMoehrke** [comment]
move to closed issue,
