### ISSUE TITLE
MHD_058: add support for Binary or Bundle to support FHIR-Documents better

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.MHD#34]
MHD_058: The profile requires that the document submitted is encoded in a FHIR Binary. Is there interest in also allowing a Bundle of type Document? This would be useful when publishing FHIR-Documents. The FHIR-Document would still need to be seralized into a Bundle of type Document, but that Bundle would not need to be further encoded into a Binary (e.g. base64 encoding). Note that the mime-type in this case would be forced to be the same mime-type as the ITI-65 Bundle, where a Document Source wants to encode ITI-65 in a mime-type that is different than the document, the Binary methodology would need to be used.

**Comment by JohnMoehrke** [comment]
a Document Responder that is not MHDS, would need to address what happens with Document Bundles. would that be deterministic? 
Would all Responders need to support Document Bundles?
Would there be any limits?

**Comment by jlamy** [comment]
Or a Document Responder that is grouped with XDR/XCDR. Good point. Adds more work for the responder for minimal benefit. Let's discuss.

**Comment by JohnMoehrke** [comment]
Leave as an Open issue

Look at Retrieve to see if text could be added explaining likely Retrieve behavior when the URL is a FHIR-Document and fhir mime types are in the GET request. Could it, Should it, WILL it, return the Document Bundle?
