### ISSUE TITLE
Document Source and entryUUID

### ISSUE THREAD

**Issue by oliveregger** [IHE/ITI.MHD#38]
**Section Number** 

https://profiles.ihe.net/ITI/MHD/a_issues.html
CP-ITI-1119: Made clear that Document Source must not populate any entryUUID.

**Issue** 
CP-ITI-1119: Made clear that Document Source must not populate any entryUUID.

According to the original CP I cannot find out the summary of the above sentence. 

In addition [Table 4.3.1-3: Sending Actor Metadata Attribute Optionality](https://profiles.ihe.net/ITI/TF/Volume3/ch-4.3.html#4.3) sets entryUUID as Required for the sending Actor.

See also discussion in [google group](https://groups.google.com/g/ititech/c/Ahy4HNJGNZM/m/9EuyII-EBgAJ)

**Proposed Change** 
Remove the summary of CP-ITI-1119 and enforce entryUUID also in MHD, see also https://github.com/IHE/ITI.MHD/issues/13. 

**Priority**:
- High: Important issue where there is major issue to be resolved. Requires discussion and debate.

**Comment by JohnMoehrke** [comment]
Move CP-ITI-1119 to closed issues, and enforce entryUUID in MHD.
