### ISSUE TITLE
Require HTTP POST for ITI-66 and ITI-67

### ISSUE THREAD

**Issue by oliveregger** [IHE/ITI.MHD#39]
**Section Number** 
https://profiles.ihe.net/ITI/MHD/ITI-66.html
https://profiles.ihe.net/ITI/MHD/ITI-67.html

**Issue** 
Message Semantics declares that:
The Document Consumer executes an HTTP GET against the .. URL

It is not clear if a Document Consumer can also execute a HTTP POST for the query and if a server shall support also a FHIR POST Query. Above sentence implies that a only a HTTP GET might be needed. 

The FHIR specification requires [both](https://www.hl7.org/fhir/http.html#search ):

`Because of the way that some user agents and proxies treat GET and POST requests, in addition to the get based search method above, servers that support search SHALL also support a POST based search:
`
For a server it is not difficult to support both methods, it should be up to the client or actual deployment or regulation which method should be chosen.

Discussion about HTTP POST in [Zulip](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Search.20via.20POST)

**Proposed Change** *
The Document Consumer executes an HTTP GET or HTTP POST ...

**Priority**:
- High: Important issue where there is major issue to be resolved. Requires discussion and debate.

**Comment by JohnMoehrke** [comment]
Need examples of POST equal to our examples of GET. Narrative code blocks, examples, and audit examples.

**Comment by JohnMoehrke** [comment]
Here is what I have added to ITI-67... Is this right?

###### 2:3.67.4.1.2.3 Example DocumentReference search

For example given:
* FHIR server root is `http://test.fhir.org/R4/fhir`
* Patient id is `9876`
* status of current
* with clinical code from loinc of 1234-5

###### 2:3.67.4.1.2.3.1 Example GET
```
GET test.fhir.net/R4/fhir/DocumentReference?patient=9876&status=current&type=http://loinc.org|1234-5
```

###### 2:3.67.4.1.2.3.2 Example POST
```
POST test.fhir.net/R4/fhir/DocumentReference?patient=9876&status=current&type=http://loinc.org|1234-5
```

###### 2:3.67.4.1.2.3.3 Example POST body
```
POST test.fhir.net/R4/fhir/DocumentReference

patient=9876&status=current&type=http://loinc.org|1234-5
```
