### ISSUE TITLE
dependency on ihe.formatcode.fhir to last published version?

### ISSUE THREAD

**Issue by oliveregger** [IHE/ITI.MHD#40]
**Section Number** 
https://profiles.ihe.net/ITI/MHD/qa.html

**Issue** 
MHD is dependent on the terminology defined in ihe.formatcode.fhir#current. current is the last built version on the ci-build. the dependency should be probably fixed to the last published version 0.2.4? 

https://profiles.ihe.net/fhir/ihe.formatcode.fhir/history.html

**Proposed Change**
Add dependency  to latest published version, maybe with an X that updated patched versions will be considered: 0.2.x

**Priority**:
- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by JohnMoehrke** [comment]
I tried to use 0.2.4, but got a build failure.

java.io.IOException: Error reading http://profiles.ihe.net/fhir/ihe.formatcode.fhir/0.2.4/package.tgz: Input is not in the .gz format

I do not know how to resolve this.

I hope that it is related to the ig-registry accepting the pull-request
    https://github.com/FHIR/ig-registry/pull/50

**Comment by JohnMoehrke** [comment]
I have removed this constraint as it was not really an important constraint. Will continue to promote the IHE FormatCode IG as formally recognized by HL7.
