### ISSUE TITLE
should MHD define a MHD connection type?

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.MHD#41]
see FHIR managed valueSet
    http://build.fhir.org/valueset-endpoint-connection-type.html

MHD could define a value in the IHE space, or we could request adding a value to the HL7 managed codeSystem

**Comment by jlamy** [comment]
Hmmm. I figured it would use hl7-fhir-rest, as a client could learn everything it needs to from the capability statement. Can it?

**Comment by JohnMoehrke** [comment]
Discussed with committee. prefer to NOT create a new connection type, but to recommend the use of the metadata capabilityStatement use. 

May need to stress this in a future CP to Appendix Z.
