### ISSUE TITLE
Complete Specify Actors/Transactions just once

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.MHD#43]
**Section Number** https://profiles.ihe.net/ITI/MHD/1_overview.html  Section 2 MHD Actors, and Transactions

**Issue** * There are two section 2's on the Overview page, and the contents of "MHD Actors and Transactions" is in complete, and what you really want comes later.

**Proposed Change**   Take the content in https://profiles.ihe.net/ITI/MHD/2_actors_and_transactions.html  and use it to replace Section 2 on https://profiles.ihe.net/ITI/MHD/1_overview.html    That way, the actors are introduced before you do use cases.   

**Priority**: Medium

**Comment by JohnMoehrke** [comment]
done
