### ISSUE TITLE
refinement suggestions for Sec 3.1 Actors

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.MHD#46]
**Section Number** https://profiles.ihe.net/ITI/MHD/2_actors_and_transactions.html

**Issue** 
1. In 3.1.x, would like to understand the rationale for itemizing the options under each actor when this information exists more succinctly in the very next section.
2. You have included the actor definition here.   Will IG's deviate from IHE's effort to harmonize actor definitions in the General Introduction?
3. We have lost Vol 1 Sec 33.1.1 Actor Descriptions and Actor Profile Requirements

**Proposed Change** *
1. Eliminate the "<actor> implementing <option>" text
1a if you keep it, then make it accurate (the Document Responder has an option)
1b. If you keep it, get rid of < actor> with no options or all options.   I don't l know what that means
2.  Link to the actor definition in the common appendix, rather than duplicating (or changing) the definition here.
2b.   If you do this, do the same with Transaction Descriptions in https://profiles.ihe.net/ITI/MHD/2_actors_and_transactions.html#transaction-descriptions
3. Remove the existing contents of https://profiles.ihe.net/ITI/MHD/2_actors_and_transactions.html#actors and replace it with "Actor Descriptions and Actor Profile Requirements.    This section was added to the Supplement Template because we often have a need to specify actor requirements that are not transaction or option-related

**Priority**: Medium

**Comment by JohnMoehrke** [comment]
2 - I think at this point we need to duplicate the text. It should be aligned. But we don't yet have a smooth way to link without duplication. A current supplement has this duplicate text, so it is not too strange, it is just strange placement.

**Comment by JohnMoehrke** [comment]
3) I am not clear which header needs to be renamed. I have renamed 33.1.1 Actors. If that is not the right header, please let me know.
