### ISSUE TITLE
Inconsistent use of "profile" vs. "implementation guide"

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.MHD#47]
**Section Number** throughout

**Issue** We still have an MHD "Profile", right?    The "implementation guide" is just the documentation vehicle for specifying it, right?     It's unclear how you decided to use one term vs another in here.
e.g.  https://profiles.ihe.net/ITI/MHD/2_actors_and_transactions.html#transaction-descriptions, you say "This section defines the actors and transactions in this implementation guide."   I think the actors are in the profile.  MHD Doc Source, MHD Doc Recipient.   Yes, the exist "in" the IG, but that's just because you have write about them on these pages.

I know this is a 'dancing on the head of a pin' argument, but we are setting precedent here for future IGs.

**Proposed Change**    You might say "IG" is a term we are going to adopt now.   Then, is "MHD Profile" even accurate anymore (I hope so).   If so, when?

**Priority**: medium

**Comment by JohnMoehrke** [comment]
We can't continue to think that this is a fight we can win. 

There is strong dissonance between IHE and HL7 use of the word "profile", and there is significant marketing pressure around "Implementation Guide". 

We can't afford to not use the term "Implementation Guide", especially in the context of the authoring and publishing solution driven by the "IG Publisher". 

IHE needs to come up with consistent ways to address and change our own thinking on this. The external community are already understanding the concepts as HL7 uses them. However the external community do think that "Implementation Guide" is something that only HL7 publishes, and they are confused on what "profile" means. Thus I think IHE needs to aggressively market that "IHE Profile" and "Implementation Guide" are the same thing. Therefore I think that IHE Profiles do need to emphasize this. 

My approach is to use "IHE Profile" and "Implementation Guide" as the same. The use of upper case "Profile" in the context of an IHE publication can be understood as "IHE Profile". The lowercase "profile" is ambiguous, most of the time referring to what the FHIR community calls a "StructureDefinition constraint" .  I don't think that IHE can stop using "IHE Profile", but I do think we can increase use of "Implementation Guide".

We need consistency rules. We need marketing of this.

**Comment by lynnfel** [comment]
I'm not looking to win or lose a fight.   If we believe Profile and Implementation Guide are two terms for the same conceptual thing, OK.   We can write 5 explanatory sentences to say that, put it in a common appendix, and then add a link to that explanation in each fhir-based document/artifact that IHE publishes.  Or, something like that.   What I'd like to avoid is using the both terms randomly (exaggerating with that) throughout the text.

**Comment by JohnMoehrke** [comment]
see https://profiles.ihe.net/GeneralIntro/ch-3.html

**Comment by JohnMoehrke** [comment]
Any further refinement will happen in final review
