### ISSUE TITLE
Appx Z - part of MHD public comment??

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.MHD#48]
**Section Number**  several

**Issue** there are numerous links into https://profiles.ihe.net/ITI/MHD/appendix_z.html.   Does that mean that content is "in scope" for this public commen t?

**Proposed Change** separate public comment for Appx Z

**Priority**: medium

**Comment by JohnMoehrke** [comment]
I expected bringing in these two appendix would cause issues.  Discussion is needed on best way to go forward. The main reason to bring them in was to enable links into the text, enabled by HTML. Leaving these in PDF seemed wrong and clunky.

**Comment by JohnMoehrke** [comment]
should we move this html rendering into the ITI/TF html publication? Somehow it would need to be marked there as trial-implementation.

**Comment by JohnMoehrke** [comment]
remove E and Z from MHD

Add Z to the publications repo, and thus staging area for profiles.ihe.net
* mark it clear as "Trial Implementation"

Update MHD links to Z to point at profiles.ihe.net Z
