### ISSUE TITLE
ITI-65: Need guidance for grouping with XDR/XCDR

### ISSUE THREAD

**Issue by jlamy** [IHE/ITI.MHD#51]
**Section Number** *11.4.1.3*

**Issue** *MHD allows grouping with XDR/XCDR in addition to XDS, but only provides details for XDS. For example, in section 11.4.1.3.1, the instructions for transforming the ITI-65 into an ITI-41 could easily be reused for at least XDR.*

**Proposed Change** *Either define XDR-on-FHIR, XCDR-on-FHIR, etc. or provide non-normative guidance to implementers to follow the XDS transformations.*

**Priority**:
- Medium

**Comment by JohnMoehrke** [comment]
this seems to be asking for a named option when none is needed. I don't mind defining grouping behaviors, this is common. But I don't think there is a need for an option.

What do you see as the grouping behaviors necessary to be said? They seem very obvious and thus not needing to be said.

**Comment by JohnMoehrke** [comment]
I changed the text to be more pattern specific than transaction specific.
