### ISSUE TITLE
ITI-65: Allow Folder Lists to have PUT request

### ISSUE THREAD

**Issue by jlamy** [IHE/ITI.MHD#55]
**Section Number** *11.4.1.2.1*

**Issue** *ITI-65 constrains each bundle entry request to POST. This would mean if an MHD Document Source wanted to add Document References to an existing Folder, it would have to do it outside an ITI-65, e.g. in a single PUT.*

**Proposed Change** *Because ITI-65 adds valuable context and provenance, we should allow Folder Lists to use the PUT request in ITI-65. Additionally, we should consider guidance that ITI-65 should be the only mechanism used to update Folder Lists. We enforce this in the eHealth Exchange, but it is a cross-community environment. It may be the case that inside a community, systems may want to allow more flexibility.*

**Priority**: Medium

**Comment by JohnMoehrke** [comment]
agreed on PUT, this was an oversite.

Comments regarding not allowing any creates/updates/deletes/queries outside of the approved MHD methods is unusual for a profile to do. Anything done outside of the profiled interactions are simply outside the profile control.  Anything done outside the profiled interactions might work, but the profile can't claim anything about that. It might work, it might not. What is the harm overall if it works or is failed?

**Comment by jlamy** [comment]
Ok, thanks. That works for me.

**Comment by JohnMoehrke** [comment]
it is the profiled way to update a Folder. All others are not part of the profiled behavior.
