### ISSUE TITLE
ITI-65: Need guidance for List.status when grouping with XDS/XDR/XCDR

### ISSUE THREAD

**Issue by jlamy** [IHE/ITI.MHD#58]
**Section Number** *15.12.6.3, 15.4.6.3, 11.4.1.3*

**Issue** *There are two issues with Folder List.status when grouping MHD with XDS/XDR/XCDR: 1. The mappings to XDS in section [15.12.6.3](https://profiles.ihe.net/ITI/MHD/StructureDefinition-IHE.MHD.Comprehensive.Folder-mappings.html#mappings-for-xds-and-mhd-mapping-xds) and [15.4.6.3](https://profiles.ihe.net/ITI/MHD/StructureDefinition-IHE.MHD.Comprehensive.SubmissionSet-mappings.html#mappings-for-xds-and-mhd-mapping-xds) do not map the value "current" to "Approved" 2. XDS Submission Sets and Folders are not allowed to be deprecated. What should happen if an ITI-65 request includes a different status?*

**Proposed Change** *1. Add mappings to 15.12.6.3 and 15.4.6.3. 2. Add guidance to reject any List.status other than "current".*

**Priority**: Medium

**Comment by JohnMoehrke** [comment]
@jlamy I am not understanding a solution.
1. The code mapping is found in Table 2:3.66.4.1.2.1-1. -- see http://build.fhir.org/ig/IHE/ITI.MHD/branches/master/ITI-66.html
2.   MHD is not the right place for rules around "not allowing deprecation". 

so I am not understanding any change to make.
