### ISSUE TITLE
ITI-65 Expected actions -- should to shall

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.MHD#60]
**Section Number** https://profiles.ihe.net/ITI/MHD/ITI-65.html#expected-actions

**Issue** change should to shall in the 1st sentence below, since the following 2 sentences contain shall

**Proposed Change** The Document Recipient should verify the FHIR resource elements for consistency with the Document Sharing metadata requirements as specified for attributes ITI TF-3: Table 4.3.1-3: “Sending Actor Metadata Attribute Optionality”. The Document Recipient that supports the “Comprehensive Metadata” or the “XDS on FHIR” Option shall validate against column “XDS DS”; otherwise the Document Recipient should validate against column “XDR MS”.

**Priority**:

- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by lynnfel** [comment]
Then, remove "otherwise".

**Comment by JohnMoehrke** [comment]
will work on wording clarity.
