### ISSUE TITLE
ITI-65: Define processing model for intendedRecipient

### ISSUE THREAD

**Issue by jlamy** [IHE/ITI.MHD#63]
**Section Number** *11.4.1.3*

**Issue** *There is a need for a minimal processing model to be defined for Submission Set List.extension:intendedRecipient. This need has been identified while working on the work item [MHD to a Federation](https://github.com/IHE/IT-Infrastructure/issues/142). In addition, there isn't a clear error or warning code that could be returned in the case a recipient was unknown or could not be reached, as there is for communities.*

**Proposed Change** *Define codes UnknownRecipient and UnreachableRecipient (may need to add these to Vol 3 for XDR to use as well, in which case just point to them). Define processing model like the following:*
* If intendedRecipient is specified, the Document Recipient SHALL make reasonable efforts to determine whether each recipient can be notified. If not possible, the Document Recipient MAY do any of the following:
  * Fail the transaction with the code UnknownRecipient or UnreachableRecipient
  * Accept the transaction with the code UnknownRecipient or UnreachableRecipient as a warning
  * Succeed silently

**Priority**: Medium

**Comment by JohnMoehrke** [comment]
Need some text that explains that this requirement applies only to DocumentRecipients that are expected to execute on notification. Meaning that for those DocumentRecipients that are just a proxy to some other technology that is responsible. For example when MHD is frontend to XDR and XDR is intended to do the notification. I think this is the right logic we desire, and I think this is what we mean by "reasonable", but I think we need to be more specific.
