### ISSUE TITLE
all grouping shoulds and shalls belong in Vol 1

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.MHD#64]
**Section Number** https://profiles.ihe.net/ITI/MHD/ITI-65.html#security-audit-considerations  Maybe in other transactions, too

**Issue**   

**Proposed Change** 
Remove the sentence starting with "Grouping..."    This belongs in Sec Considerations in Vol 1:
The security audit criteria are similar to those for the Provide and Register Document Set-b ITI-41 transaction as this transaction does export a document. Grouping a Document Source or Document Recipient with an ATNA Secure Node or Secure Application is recommended, but not mandated.

I know this was copied from 'old' MHD, but let's fix it now

- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by JohnMoehrke** [comment]
Shouldn't these sections be mandated WHEN grouped with ATNA?
