### ISSUE TITLE
ITI-66 - code req'd in the request?

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.MHD#65]
**Section Number** https://profiles.ihe.net/ITI/MHD/ITI-66.html#query-search-parameters

**Issue** The Document Consumer may supply, and the Document Responder shall be capable of processing all query parameters listed below.

**Proposed Change** The "code" parameter should be required for the Source, right?   Don't you want to  always know whether you are querying for a List with a code of  'folder; or of 'submissionset'?

**Priority**:

- Low: Typo or other minor classification that an editor can manage. Requires no group discussion.

**Comment by JohnMoehrke** [comment]
yes, patient and code should be required.
