### ISSUE TITLE
ITI-66: two queries, one list of parameters

### ISSUE THREAD

**Issue by lynnfel** [IHE/ITI.MHD#66]
**Section Number** https://profiles.ihe.net/ITI/MHD/ITI-66.html#query-search-parameters

**Issue** ITI-66 can be used to search for List Resources of type 'submissionset' or 'folder'; however the list of search parameters is a superset and not all listed parameters are appropriate for each query, e.g. parameter sourceId is n/a for folders.

**Proposed Change** I think the two queries should be differentiated.  Maybe a table with all queries with columns for parameter, the definition, and the two queries (indicating which parameter is R, O, or NA for each)

**Priority**:

- Medium: Significant issue or clarification. Requires discussion, but should not lead to long debate.

**Comment by JohnMoehrke** [comment]
is this really a problem?  I am not understanding the problem with extra query parameters that have no effect sometimes.
a) In the case of MHDS, these query parameters will all function according to FHIR Core
b) In the case of MHD as an API to classic XD*, some parameters will be silently ignored.

do I simply need to say that?

**Comment by JohnMoehrke** [comment]
update section http://build.fhir.org/ig/IHE/ITI.MHD/branches/master/ITI-66.html#23664131-xds-on-fhir-option

add a Note 3, parameters specific to "submissionset" shall be silently ignored.
