### ISSUE TITLE
Where is the definition of Must Support?

### ISSUE THREAD

**Issue by jlamy** [IHE/ITI.MHD#74]
**Section Number** *Not sure*

**Issue** *Profiles are required to make clear what Must Support means to them. Where is this definition for MHD?*

**Proposed Change** *Make the definition explicit.*

**Priority**: Low

**Comment by JohnMoehrke** [comment]
will bring in. I though it was already said in Appendix Z, but it seems to be missing. 
Would stating the default IHE position on MustSupport in Appendix Z with a reference from MHD be a good solution?
