### ISSUE TITLE
Can StructureDefinition constraints suffice for optionality?

### ISSUE THREAD

**Issue by jlamy** [IHE/ITI.MHD#75]
**Section Number** *11.4.1.2, 11.4.1.3 for ITI-65, but other transactions as well*

**Issue** *To determine the optionality for metadata elements, the implementer has to look in Vol 3 for XDS attributes’ optionality, then the mapping tables to map them to FHIR elements, then finally at the cardinality in the StructureDefinitions. Is this all necessary? Could the StructureDefinitions be sufficient, if they have already taken this all into account?*

**Proposed Change** *Consider just letting the StructureDefinitions do the work of constraining if possible. If it is considered useful to point out that these constraints happen to correspond to XDS Vol 3 constraints, do so informatively.*

**Priority**: Low

**Comment by JohnMoehrke** [comment]
The capability statements are written to be aligned. I think that we must do both. The Volume 3 is the normative text for all of the Document Sharing profiles. The capability statement is only visible in MHD.  If there is a dissonance between the two, the Volume 3 would be considered more normative.

**Comment by JohnMoehrke** [comment]
Need a mechanism to indicate WHEN a conformance resource is intended to be subset of normative statements, or a subset.

Artifact page explain use of Draft/Active status. 
* Resource in Draft status --> Not intended to be consistent
* Resource in Active status --> Intended to be consistent with normative text

**Comment by JohnMoehrke** [comment]
There is no status of a resource.... so the best that can be done is to have clear resource description. I intend to do that.

**Comment by JohnMoehrke** [comment]
all resources have complete definitions and descriptions.
