### ISSUE TITLE
Questions about mappings

### ISSUE THREAD

**Issue by jlamy** [IHE/ITI.MHD#76]
**Section Number** *15.11.6, 15.23.6*

**Issue**
* Why are there two mappings for MHD-XDS? For example: 15.23.6.7 and 15.23.6.8. They appear almost identical, and I don't understand when I would need to use one versus the other.
* Why are there separate mapping pages for comprehensive (15.11.6) and minimal (15.23.6) DocumentReference? I don’t think the mappings are different based on the options. Is this a tooling limitation?

**Proposed Change** *Remove unnecessary duplicates.*

**Priority**: Low

**Comment by JohnMoehrke** [comment]
The two mappings come from different places.

The mapping titled "Mappings for XDS metadata equivalent (http://ihe.net/xds)" comes from FHIR Core

The mapping titled "Mappings for XDS and MHD Mapping (XDS)" comes from MHD

There is no way to remove the mappings in FHIR Core. The mapping given in MHD is aligned with MHD more detailed and modern understanding.

**Comment by JohnMoehrke** [comment]
@costateixeira has agreed to look into some possible ways for us to manipulate what is on the mapping tab. This might take some time to achieve. So this solution might be applied after publication. This will not be a huge problem.

**Comment by JohnMoehrke** [comment]
https://github.com/HL7/fhir-ig-publisher/issues/260

**Comment by JohnMoehrke** [comment]
closing this one. Will address when HL7/fhir-ig-publisher#260 resolves
