### ISSUE TITLE
Issues with examples

### ISSUE THREAD

**Issue by jlamy** [IHE/ITI.MHD#82]
**Section Number** *http://build.fhir.org/ig/IHE/ITI.MHD/artifacts.html#example-example-instances*

**Issue** *A couple issues with the examples:*
- Are they all used? From the artifacts page I see things like Example List - 593cd04e-b696-45c1-bc32-39e55a340a44 and Example Bundle - ex-dummyProvideDocumentBundle. I don't see a way to search for if or where these are referenced.
- The Example ITI-65 Bundle - ex-minimalProvideDocumentBundle doesn't include a Submission Set (nor for that matter does the dummy example)

**Proposed Change** *Provide a good ITI-65 request. If there is an IG build tool config setting for computing backlinks, please set it.*

**Priority**: Low

**Comment by JohnMoehrke** [comment]
This is a complaint against the IG publisher.   There is no mechanism available to provide narrative on the Artifact Index page. The IG publisher does not show breadcrumbs back to the structureDefinition it validates against.

When you navigate from the structureDefinition, you can see all the examples that are compliant with that structureDefinition.

Is this a critical to fix problem?

**Comment by JohnMoehrke** [comment]
I intend to add descriptions to all examples. This description will explain their intent. 
There is a request to the IG builder https://github.com/HL7/ig-template-base/issues/156
