### ISSUE TITLE
test plan

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.MHD#83]
recommend the test plan be removed. 

It likely is not causing any harm

**Comment by JohnMoehrke** [comment]
Add clear indicatino of the formal test plans/tools/procedures for IHE @lynnfel 

Leave the text (use IG builder mechanism to tag this)

**Comment by lynnfel** [comment]
I will assume that the IG imposes no required structure to the sections on the Test Plan page, unless you tell me otherwise.  e.g. there is nothing that would prevent adding a section labeled "Available test tools"

**Comment by JohnMoehrke** [comment]
correct. There is no expectation on the format of this page
