### ISSUE TITLE
Document Source must calculate size/hash

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.MHD#85]
The Document Source in MHD must calculate and populate the size and hash values. Where as in XDS the Document Source may allow the Repository to calculate these prior to it forwarding on to the Registry (see https://profiles.ihe.net/ITI/TF/Volume2/ITI-41.html#3.41.4.1.3.2).

**Comment by JohnMoehrke** [comment]
The Document Recipient should have a rule to test size/hash if they are provided - https://profiles.ihe.net/ITI/TF/Volume2/ITI-41.html#3.41.4.1.3

**Comment by oliveregger** [comment]
@JohnMoehrke why must the MHD Document Source calculate and populate the size and hash values?

**Comment by JohnMoehrke** [comment]
I was looking at equivalence with XDS. so I guess the requirement could be MHDS based.
but an off-the-shelf FHIR server won't add it. And now, if there is no size and hash, then the document appears to be a on-demand entry.

**Comment by JohnMoehrke** [comment]
could still encourage clients to calculate it... right?

**Comment by oliveregger** [comment]
Yes. But with a possible grouping of MDH Document Recipient and XDS Document Source i would find it very strong if it is a must for a MHD Document Source to populate hash/size.

**Comment by JohnMoehrke** [comment]
right. so agree to soften. I could be convinced that it is not to be said anything about in MHD, as MHDS is where it should be said (It is not said in MHDS).

**Comment by JohnMoehrke** [comment]
I don't find any reason why calculation at the Document Source is wrong, so I have added this and made a few more clarifications on consumption.
