### ISSUE TITLE
allow DocumentReference.docStatus

### ISSUE THREAD

**Issue by simoneOnFhir** [IHE/ITI.MHD#96]
On a similar note to https://github.com/IHE/ITI.MHD/issues/88
Please consider removing the ..0 constraint on docStatus.

The information is relevant for internal document exchange within hospitals.
Implementers shouldn't have to specifically remove this information in order to share documents via MHD.
While the information my not be needed in MHD context and cannot be mapped to XDS, it shouldn't limit interoperability with use cases that require this information.

**Comment by JohnMoehrke** [comment]
it is always acceptable to return non-compliant DocumentReference resources. 

MHD does not allow the docStatus as it is representing document lifecycle methods that are conflicting with the .relatesTo method of document lifecycle. MHD aligns with XDS which uses the .relatesTo method.   The .relatesTo method enables identifying the new document, and preserves the old document. The .docStatus method does not have a way to indicate the replacement document, and supports revisions within the same DocumentReference.
