### ISSUE TITLE
Correct MHD sourceId and designationType search parameter FHIR paths

### ISSUE THREAD

**Issue by JohnMoehrke** [IHE/ITI.MHD#97]
IHE Change Proposal submitted by brian.lind@infor.com
	

Tracking information:
IHE Domain
ITI
Change Proposal ID:
CP-DOM-xxx (assigned by Domain Technical Committee)
Change Proposal Status:
Submitted
Date of last update:

Person assigned:
(assigned by Domain Technical Committee)

Change Proposal Summary information:
Correct MHD sourceId and designationType search parameter FHIR paths
Submitter’s Name(s) and e-mail address(es):
Brian A. Lind – brian.lind@infor.com
Submission Date:
11/10/2021
Integration Profile(s) affected:
Mobile access to Health Documents (MHD) 
4.0.1, 2021-06-04
Actor(s) affected:

IHE Technical Framework or Supplement modified:

Volume(s) and Section(s) affected:
ITI-66
Rationale for Change:
The MHD implementation guide SearchParameter resources for sourceId and designationType have incorrect FHIR paths in the expression fields. For the HAPI FHIR JPA server, the paths need to be corrected to support searching on the “http://profiles.ihe.net/ITI/MHD/StructureDefinition/ihe-designationType” and “http://profiles.ihe.net/ITI/MHD/StructureDefinition/ihe-sourceId” extensions.

For “http://profiles.ihe.net/ITI/MHD/SearchParameter/List-DesignationType” resource in the MHD implementation guide:
Replace “expression: (extension('http://profiles.ihe.net/ITI/MHD/StructureDefinition/DesignationType').value as CodeableConcept)” 
with “expression: extension.where(url='http://profiles.ihe.net/ITI/MHD/StructureDefinition/ihe-designationType').value”
For “http://profiles.ihe.net/ITI/MHD/SearchParameter/List-SourceId” resource in the MHD implementation guide:
Replace “expression: (extension('http://profiles.ihe.net/ITI/MHD/StructureDefinition/SourceId').value as Reference)” 
with “extension.where(url='http://profiles.ihe.net/ITI/MHD/StructureDefinition/ihe-sourceId').value”

**Comment by oliveregger** [comment]
The extension function shortcut is defined [here](https://www.hl7.org/fhir/fhirpath.html#functions), so the FHIRPath expressions are not incorrect. It could be that for the HAPI FHIR JPA server is not supporting the extension function?

**Comment by oliveregger** [comment]
mCSD uses also the extension() construct.

**Comment by lukeaduncan** [comment]
The FHIR example for SearchParameters uses this function as well:  https://www.hl7.org/fhir/searchparameter-example-extension.html

**Comment by JohnMoehrke** [comment]
I use this pattern in ITI.BasicAudit as well

**Comment by JohnMoehrke** [comment]
Discussion on ITI CP meeting -- Trend of the discussion is to not accept this request. More compelling facts would be needed.

**Comment by JohnMoehrke** [comment]
@oliveregger What is your current view on this. Should the committee reject this CP and pull-request?

**Comment by oliveregger** [comment]
will reject it because it is standard fhirpath with the extension, decided at f2f
