### ISSUE TITLE
FHIR Identifier Type Appendix link description

### ISSUE THREAD

**Issue by skbhaskarla** [IHE/ITI.MHD#99]
IHE MHD 
3:4.5 FHIR Maps
https://profiles.ihe.net/ITI/MHD/32_fhir_maps.html#3451-metadata-object-types-mapped-to-fhir

"see ITI TF-2: Appendix E.3 “FHIR Identifier Type”" should be Appendix Z.9.1 Identifier Type. Although the description seems to be incorrect, the hyperlink navigates to the proper section.

**Comment by JohnMoehrke** [comment]
the link is to the PDF (which had E updates and Z, but was titled Z).

that PDF has been published in html, but E is in a different place. - https://profiles.ihe.net/ITI/TF/Volume2/ch-E.html#E.3
